### ISSUE TITLE
Fix metadata to show correct domain

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/ghost-jsdelivr-theme#5]
Source code uses the wrong domain everywhere jsdelivr-blog.ghost.io/
Need to fix that and set jsdelivr.com as canonical

**Comment by MartinKolarik** [comment]
This is correct. The links are rewritten by the proxy and should not be set at the theme level. I only see a problem with the social media metadata in head since those use custom semantics and can't be that easily rewritten. They also seem to be not configurable at all at the theme level as ghost just outputs all of it as one big chunk of text.

**Comment by MartinKolarik** [comment]
Should be ok now.
